chore: Add obsidian planner templates #1

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -17,9 +17,35 @@ BLUE='\033[1;34m'
 BOLD='\033[1m'
 RESET='\033[0m'
 
+echo "Running full pre-commit from commit-msg hook..."
+uv run pre-commit run --all-files
+STATUS=$?
+
+if [ "$STATUS" -ne 0 ]; then
+  echo "❌ pre-commit hook failed"
+  exit "$STATUS"
+fi
+# run togit-parser in files staged for commit:
+if command -v togit-parser >/dev/null 2>&1; then
+  echo
+  echo -e "${GREEN}${BOLD} === RUNNING togit-parser ON STAGED FILES... === ${RESET}"
+
+  # Get all staged files
+  STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
+
+  if [[ -n "$STAGED_FILES" ]]; then
+    echo "$STAGED_FILES" | xargs togit-parser
+    echo "done."
+  fi
+else
+  echo -e "${BLUE}togit-parser not found in PATH, skipping...${RESET}"
+fi
+
 # Enforce conventional commit format
 TYPES="feat|fix|chore|docs|style|refactor|perf|test"
 errors=0
+echo
+echo -e "${GREEN}${BOLD} === RUNNING COMMIT FORMAT CHECK... === ${RESET}"
 if ! echo "$COMMIT_MSG" | grep -Eq "^($TYPES)(\([a-z0-9-]+\))?: .+"; then
   echo
   echo -e "${RED}${BOLD}✖ Invalid Commit Message Format${RESET}"
@@ -30,13 +56,17 @@ if ! echo "$COMMIT_MSG" | grep -Eq "^($TYPES)(\([a-z0-9-]+\))?: .+"; then
   # sum 1 to errors
   errors=$((errors + 1))
 fi
+echo "done."
 
 # Extract referenced tasks
 REF_TASKS=$(grep -oE "#[0-9]+" <<<"$COMMIT_MSG" | sort -u)
 REF_TASKS_ARRAY=($REF_TASKS)
 
+# Check if tasks are referenced
+echo
+echo -e "${GREEN}${BOLD} === RUNNING TASK REFERENCE CHECK... === ${RESET}"
+
 if [[ ${#REF_TASKS_ARRAY[@]} -lt 1 ]]; then
-  echo
   echo -e "${RED}${BOLD}✖ Missing Task Reference${RESET}"
   echo -e "   Every commit must reference at least one task ID (e.g. ${GREEN}#123${RESET})"
   echo
@@ -47,15 +77,26 @@ if [[ ${#REF_TASKS_ARRAY[@]} -lt 1 ]]; then
   errors=$((errors + 1))
   # exit 1
 fi
+echo "done."
 # check if errors
+
 if [[ "$errors" -gt 0 ]]; then
   echo
   echo -e "${RED}${BOLD}✖ Please fix the above errors and try again. To skip: --no-verify${RESET}"
   exit 1
 fi
 
+echo
+echo -e "${GREEN}${BOLD} === COMMIT MSG OK. CHECKING TASKS TO CLOSE IF ANY... === ${RESET}"
 # Extract tasks explicitly within [do #n #n2] or [done #n #n2]
 DO_BLOCKS=$(grep -oP '\[(do|done)\s+#[0-9]+((\s+#[0-9]+)*)\]' <<<"$COMMIT_MSG")
+# check if do | done blocks are present
+if [[ -n "$DO_BLOCKS" ]]; then
+  echo -e "${GREEN}${BOLD}✔ Found tasks to close: ${DO_BLOCKS[*]}${RESET}"
+else
+  echo -e "${BLUE}${BOLD}No tasks to close.${RESET}"
+  exit 0
+fi
 
 DO_TASKS=()
 for block in $DO_BLOCKS; do
